### ISSUE TITLE
How to update or reload my table with new data source

### ISSUE THREAD

**Issue by RanjitKadam** [graetzer/iOS-MensaPlanner#1]
Hey, firstly very thanks for the project. Secondly I want to know, how we can updated my tableView with new source when I swipe or click on any of the tabs on the top.

**Comment by graetzer** [comment]
You sure you're commenting on the right project? Just change your data in didShowViewController and call `self.tableView.reloadData()`

**Comment by RanjitKadam** [comment]
Yes I am 100% sure. But didShowViewController is not called.  @graetzer . I tested in your project

**Comment by graetzer** [comment]
well if you had read my other answer, you would know that you have to set the `delegate` property.

**Comment by RanjitKadam** [comment]
ok thanks got it :)

**Comment by RanjitKadam** [comment]
@graetzer I am not understanding how to reload tableView which is in another ViewController. I tried using NSNotification, but it is called multiple times. So can you throw some light on this.

**Comment by graetzer** [comment]
If it's called multiple times, you're calling it multiple times. Use the XCode debugger to figure it our.
Beyond that I can't help you

**Comment by RanjitKadam** [comment]
@graetzer , I debuged, its called multiple times because , the delegate function func viewController(page:Int) -> UIViewController { } is called multiple times. I guess this depends on the tabArray data. Please correct me if I am wrong. I am trying to understand your code.

**Comment by graetzer** [comment]
This func is called once for every view controller you want to include.
Not sure what you are trying to achieve here, this is stuff is really not difficult.

**Comment by RanjitKadam** [comment]
@graetzer my requirement is that I want to have only one tableViewController and on swipe i just want to reload the table with new data. Is that possible?

**Comment by graetzer** [comment]
I don't understand what you want to achieve.
You can have multiple view controllers and have them reload when they become visible.

**Comment by RanjitKadam** [comment]
Ok we can do that too. But I am not understanding how will we get to know on swipe, which viewController is visible? Because I am using UITableViewController multiple times.@graetzer

**Comment by graetzer** [comment]
Doesn't `func didShowViewController(page: Int)` tell this to you, every time the view controller becomes visible?
