### ISSUE TITLE
How to refresh tabs data.

### ISSUE THREAD

**Issue by RanjitKadam** [graetzer/iOS-MensaPlanner#3]
I gone through the app, So the tab data is already set and its static. What if the tab data is dynamic and I need to refresh it. How can we do this.

**Comment by graetzer** [comment]
The method  [reloadData()](https://github.com/graetzer/iOS-MensaPlanner/blob/master/External/SGViewPager/SGTabbedPager.swift#L127) triggers a reload of all Views.
You should ask this stuff in the appropriate repo: https://github.com/graetzer/SGViewPager
